import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { BackgroundEffect } from "@/components/background/BackgroundEffect";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BackgroundEffect />
        <Navbar />

        {children}
      </body>
    </html>
  );
}
